version: '3'
services:
  nextjs:
    build: .
    container_name: "frontend"
    environment:
      - TZ=Asia/Taipei
    ports:
      - "64550:64550"
    volumes:
      - .:/home/nextJs 
    command: bash "/home/nextJs/nextjs_env.sh" 
    
